<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>AdminLTE | Dashboard</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <link href="/adm/css/bootstrap/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <link href="/adm/css/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
    <link href="/adm/css/admin.css" rel="stylesheet" type="text/css"/>
</head>

<body class="skin-blue">
    <!-- header logo: style can be found in header.less -->
    <header class="header">
        <span class="navbar-brand">
            <img alt="t42base CMF" src="/adm/img/t4logo.png">&nbsp;t4 CMF
        </span>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
            <div class="navbar-left">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#">
                            View site
                            <i class="fa fa-share-square-o"></i>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="navbar-right">
                <ul class="nav navbar-nav">
                    <!-- User Account: style can be found in dropdown.less -->
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="glyphicon glyphicon-user"></i>
                            <span>Admin <i class="caret"></i></span>
                        </a>
                        <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                            <li role="presentation">
                                <a role="menuitem" tabindex="-1" href="#"><i class="fa fa-pencil-square-o"></i>Change password</a>
                            </li>
                            <li role="presentation">
                                <a role="menuitem" tabindex="-1" href="#"><i class="fa fa-sign-out"></i>Log out</a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>

    <div class="wrapper row-offcanvas row-offcanvas-left">
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="left-side sidebar-offcanvas">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">

                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu">
                    <li class="active">
                        <a href="#">
                            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-cog"></i> <span>Application</span>
                        </a>
                    </li>
                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>

        <!-- Right side column. Contains the navbar and content of the page -->
        <aside class="right-side">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <nav class="module navbar navbar-default" role="navigation">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <a class="navbar-brand" href="#"><i class="fa fa-cog"></i> Application</a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="#">Php info</a></li>
                            <li><a href="#">Test mail</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
            </section>

            <hr>
            <footer>
                <p class="text-muted"><a href="https://github.com/t4web/Admin" target="_blank">t4web/admin</a> module, theme by <a href="http://almsaeedstudio.com/" target="_blank">Almsaeed Studio</a></p>
            </footer>
        </aside>
    <!-- /.right-side -->
    </div>
    <!-- ./wrapper -->

    <script src="/adm/js/plugins/jquery/jquery.min.js"></script>
    <script src="/adm/js/plugins/bootstrap/bootstrap.min.js" type="text/javascript"></script>
    <script src="/adm/js/plugins/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
</body>
</html>
