<!-- Content Header (Page header) -->
<section class="content-header">
    <nav class="module navbar navbar-default" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="#"><i class="fa fa-cog"></i> Admin</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Php info</a></li>
                <li><a href="#">Test mail</a></li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </nav>

</section>

<section class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="box box-solid">
                <div class="box-body">
                    <?= $this->info; ?>
                </div>
            </div>
        </div>
    </div>
</section>
